spring.application.name=31-Student-Repository-With-Method-Name-Query-Generation

# Database config....
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/spring_db
spring.datasource.username=root
spring.datasource.password=root

# Spring Data JPA Config..
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true