# Admin related configurations
admin.url=http://admin.tca.com/
admin.port=8081
admin.userName=TCA-ADMIN
admin.password=ADMIN@TCA

# Email configuration
email.smtpHost=smtp.google.com
email.port=7070
email.toAddress=receiver@email.com
email.fromAddress=sender@email.com