package com.tca;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);

        /*
            (Spring Data JPA 4 : Hibernate 7.x)
            GeneratedValue : Strategy = IDENTITY

            For mySQL/mariaDB :
                Hibernate:
                create table student (
                    id bigint not null auto_increment,
                    birth_date date not null,
                    city varchar(32) not null,
                    gender tinyint not null check ((gender between 0 and 2)),
                    name varchar(32) not null,
                    per FLOAT CHECK(PER >= 0 AND PER <= 100),

                    primary key (id)
                  ) engine=InnoDB

                  we can see that Hibernate internally uses auto_increment.
                  which is the standard approach of key generation in mySQL / mariaDB


              For postgreSQL:
                create table student (
                    id bigint generated by default as identity,
                    birth_date date not null,
                    city varchar(32) not null,
                    gender smallint not null check ((gender between 0 and 2)),
                    name varchar(32) not null,
                    per FLOAT CHECK(PER >= 0 AND PER <= 100),
                    primary key (id)
                )

            For PostgreSQL hibernate uses identity (postgreSQL keyword),
            in older hibernate version, it was using serial.

         */

    }

}
